### ISSUE TITLE
V0.0 not found?

### ISSUE THREAD

**Issue by sooyj** [CS2103JAN2017-W13-B2/main#3]
Dear Team,

I couldnt locate your V0.0 deliverables. Please note the few major things to do:

a. Change the "addressbook level 4" repo to "main".

b. Update User Guide and selected section of the Developer Guide.

c. Use git tag to indicate your have a ready V0.0 for us to review.

Please let me know if your team run into any problem.

**Comment by clementtan** [comment]
Hi,

1) repo name changed to "main"

2) tag for v0.0 created (the PR and merge was done 5 days ago, only the tag was not created)
